WNYC-177 tracking on play, pause, ended
nypublicradio/wnyc-vue-3 pull request #143
Opened 2024-01-24 18:54 UTC by kimlarocca

https://nypublicradio-digital.atlassian.net/browse/WNYC-177

2024-01-29 22:36 UTC, bonomite requested changes
check out the comments. The login/signup components have emits you can use instead of a flat "@click"

2024-01-29 22:36 UTC, bonomite commented on components/Signup.vue
> +        @click="onSignup('google')"
use these VLoginWithProvider emits to track the proper event: ["submit-click", "submit-error", "submit-success"]

2024-01-29 22:36 UTC, bonomite commented on components/Signup.vue
> +        @click="onSignup('apple')"
use these VLoginWithProvider emits to track the proper event: ["submit-click", "submit-error", "submit-success"]

2024-01-29 22:36 UTC, bonomite commented on components/Signup.vue
> +        @click="onSignup('email')"
use these VSignupWithEmail emits to track the proper event: [  'submit-click',  'submit-error',  'submit-success',  'login-success',]

2024-01-30 15:41 UTC, kimlarocca commented on components/Signup.vue
> +        @click="onSignup('google')"
ok done!

2024-01-30 15:41 UTC, kimlarocca commented on components/Signup.vue
> +        @click="onSignup('email')"
ok done!

2024-01-30 15:42 UTC, kimlarocca commented on components/Signup.vue
> +        @click="onSignup('apple')"
ok done!

2024-02-01 14:14 UTC, bonomite approved these changes
cool

2024-02-01 14:32 UTC, merged