Kim/story details
nypublicradio/wnyc-vue-3 pull request #71
Opened 2023-09-11 16:59 UTC by kimlarocca

2023-09-11 19:46 UTC, bonomite commented on assets/scss/global.scss
> +  background: rgba(234, 234, 234, 1);
use var(--stroke) which will be #1b223c in dark mode... 

if we want the stroke color to be the same in dark mode, use var(--stroke-500)

2023-09-11 19:52 UTC, bonomite commented on pages/story/[slug].vue
> +      <p class="story-page-date mb-3">
we can use the PipeData.vue component here

2023-09-11 19:58 UTC, bonomite commented on pages/story/[slug].vue
> +const formatDate = (date) => {
not need when using the PipeData.vue component below that already uses the howLongAgo helper function

2023-09-11 20:06 UTC, bonomite commented on pages/story/[slug].vue
> +    <div class="p-3 flex align-items-center">
replace with 

const backHome = () => {
 // gtag tracking here
 navigateTo('/home') 
 }
<Button label="Home" icon="pi pi-chevron-left" @click="() => {backHome}" />

2023-09-11 20:06 UTC, bonomite commented on pages/story/[slug].vue
> +    <div class="p-3 flex align-items-center">
you can delete the arrow svg file as well

2023-09-11 20:08 UTC, bonomite commented on pages/story/[slug].vue
> +      <p class="story-page-author mb-4">
replace with VByline.vue component from the main-v2 branch of the DS

2023-09-11 20:17 UTC, bonomite requested changes
a few comments... let me know if you need any help with any of it. Thanks!

2023-09-12 14:01 UTC, kimlarocca commented on pages/story/[slug].vue
> +      <p class="story-page-author mb-4">
done!

2023-09-12 14:01 UTC, kimlarocca commented on assets/scss/global.scss
> +  background: rgba(234, 234, 234, 1);
ok!

2023-09-12 14:17 UTC, kimlarocca commented on pages/story/[slug].vue
> +      <p class="story-page-date mb-3">
got it!

2023-09-13 15:59 UTC, bonomite approved these changes
good for now. I made a few tiny updates on the branch...

2023-09-13 15:59 UTC, merged